package com.smitnk.motioncanvas.drawing

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import java.util.concurrent.ConcurrentHashMap
import com.smitnk.motioncanvas.DrawPoint
import com.smitnk.motioncanvas.DrawStroke

/**
 * Session cache for geometry generated by the real OpenToonz native engine.
 * It avoids storing native objects in project JSON; persisted strokes can be
 * regenerated from their original input points when first displayed.
 */
object OpenToonzStrokeCache {
    private val cache = ConcurrentHashMap<String, OpenToonzDrawingEngine.GeneratedStroke>()

    fun put(id: String, stroke: OpenToonzDrawingEngine.GeneratedStroke) {
        cache[id] = stroke
    }

    fun get(id: String): OpenToonzDrawingEngine.GeneratedStroke? = cache[id]

    fun clear() = cache.clear()

    fun getOrGenerate(stroke: DrawStroke): OpenToonzDrawingEngine.GeneratedStroke? {
        cache[stroke.id]?.let { return it }
        // OpenToonz interpolation is used for normal strokes. Keep very short
        // persisted/tap strokes on the safe display fallback because they do not contain
        // enough geometry for a stable vector interpolation and must never crash editor entry.
        if (!OpenToonzDrawingEngine.isNativeAvailable() || stroke.points.size < 4) return null
        return runCatching {
            OpenToonzDrawingEngine.generateStroke(
                points = stroke.points,
                baseSize = stroke.strokeWidth,
                color = stroke.color,
                opacity = stroke.alpha,
                isVector = !stroke.isEraser
            )
        }.onSuccess { generated ->
            cache[stroke.id] = generated
        }.getOrNull()
    }
}
