package com.smitnk.motioncanvas.drawing

import androidx.compose.ui.geometry.Offset
import com.smitnk.motioncanvas.DrawPoint
import com.smitnk.motioncanvas.DrawStroke
import java.util.concurrent.ConcurrentHashMap

/**
 * Session cache for geometry generated by the real OpenToonz native engine.
 * It avoids storing native objects in project JSON; persisted strokes can be
 * regenerated from their original input points when first displayed.
 *
 * OpenToonz remains the primary/authoritative stroke generator. The Kotlin
 * engine is used only when the native engine is unavailable or a native
 * generation call fails, so a device-side native loading problem cannot make
 * the canvas visually empty.
 */
object OpenToonzStrokeCache {
    private val cache = ConcurrentHashMap<String, OpenToonzDrawingEngine.GeneratedStroke>()

    fun put(id: String, stroke: OpenToonzDrawingEngine.GeneratedStroke) {
        cache[id] = stroke
    }

    fun get(id: String): OpenToonzDrawingEngine.GeneratedStroke? = cache[id]

    fun clear() = cache.clear()

    fun getOrGenerate(stroke: DrawStroke): OpenToonzDrawingEngine.GeneratedStroke? {
        cache[stroke.id]?.let { return it }
        if (stroke.points.size < 2) return null

        if (OpenToonzDrawingEngine.isNativeAvailable() && stroke.points.size >= 4) {
            runCatching {
                OpenToonzDrawingEngine.generateStroke(
                    points = stroke.points,
                    baseSize = stroke.strokeWidth,
                    color = stroke.color,
                    opacity = stroke.alpha,
                    isVector = !stroke.isEraser
                )
            }.getOrNull()?.let {
                cache[stroke.id] = it
                return it
            }
        }

        // Software fallback only. This does not replace OpenToonz when the native
        // engine is available; it prevents native-load/runtime failures from
        // dropping an otherwise valid visible stroke.
        return runCatching {
            val smoothed = OpenSourceDrawingEngine.smooth(
                stroke.points.map { Offset(it.x, it.y) }
            )
            OpenSourceDrawingEngine.toGeneratedStroke(smoothed, stroke)
                .also { cache[stroke.id] = it }
        }.getOrNull()
    }
}
